-- Generated by matugen — do not edit directly, edit matugen/templates/hyprland-colors.lua.in
---@module 'hl'

hl.config({
    general = {
        col = {
            active_border = "rgb(fe8019)",
            inactive_border = "rgba(7c6f64CC)",
        },
    },
})
