-- Generated by matugen — do not edit directly, edit matugen/templates/hyprland-colors.lua.in
---@module 'hl'

hl.config({
    general = {
        col = {
            active_border = "rgb(cba6f7)",
            inactive_border = "rgba(6c7086CC)",
        },
    },
})
