-- Generated by matugen — do not edit directly, edit matugen/templates/hyprland-colors.lua.in
---@module 'hl'

hl.config({
    general = {
        col = {
            active_border = "rgb(f0bf6d)",
            inactive_border = "rgba(4e4539CC)",
        },
    },
})
