splash = false
preload = /home/jjsanchezc/Dotfiles/hypr/Wallpapers/catppuccin/CT - Prgramming penguin.jpeg
wallpaper = ,contain:/home/jjsanchezc/Dotfiles/hypr/Wallpapers/catppuccin/CT - Prgramming penguin.jpeg
