splash = false
preload = /home/jjsanchezc/Dotfiles/hypr/Wallpapers/gruvbox/GB Light - Smoking anime girl.jpeg
wallpaper = ,contain:/home/jjsanchezc/Dotfiles/hypr/Wallpapers/gruvbox/GB Light - Smoking anime girl.jpeg
