$accent = rgb(cba6f7)
$accentAlpha = rgba(203, 166, 247, 0.8)
$text = rgb(cdd6f4)
$background = rgb(1e1e2e)
$font = JetBrainsMono Nerd Font

# GENERAL
general {
    disable_loading_bar = true
    hide_cursor = true
}

# BACKGROUND
background {
    monitor =
    path = ~/Dotfiles/hypr/Wallpapers/dark/allmight-dark.jpg
    blur_passes = 0
}

# TIME
label {
    monitor =
    text = $TIME12
    color = $accent
    font_size = 65
    font_family = $font
    position = 0, -100
    halign = center
    valign = top
}

# DATE
label {
    monitor =
    text = cmd[update:3600000] date +"%A, %d %B %Y"
    color = $text
    font_size = 25
    font_family = $font
    position = 0, -188
    halign = center
    valign = top
}

# USER AVATAR

image {
    monitor =
    path = ~/.face
    size = 125
    border_color = $accent

    position = 0, 94
    halign = center
    valign = center
}

# INPUT FIELD
input-field {
    monitor =
    size = 294, 63
    outline_thickness = 3
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgb(313244)
    inner_color = rgb(1e1e2e)
    font_color = rgb(cdd6f4)
    fade_on_empty = false
    placeholder_text = Logged in as $USER
    hide_input = false
    check_color = $accent
    fail_color = rgb(f38ba8)
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    font_family = monospace
    capslock_color = rgb(f9e2af)
    position = 0, -44
    halign = center
    valign = center
}
