$accent = rgb(fe8019)
$accentAlpha = rgba(254, 128, 25, 0.8)
$text = rgb(ebdbb2)
$background = rgb(282828)
$font = JetBrainsMono Nerd Font

# GENERAL
general {
    disable_loading_bar = true
    hide_cursor = true
}

# BACKGROUND
background {
    monitor =
    path = ~/Dotfiles/hypr/Wallpapers/dark/allmight-dark.jpg
    blur_passes = 0
}

# TIME
label {
    monitor =
    text = $TIME12
    color = $accent
    font_size = 52
    font_family = $font
    position = 0, -80
    halign = center
    valign = top
}

# DATE
label {
    monitor =
    text = cmd[update:3600000] date +"%A, %d %B %Y"
    color = $text
    font_size = 20
    font_family = $font
    position = 0, -150
    halign = center
    valign = top
}

# USER AVATAR

image {
    monitor =
    path = ~/.face
    size = 100
    border_color = $accent

    position = 0, 75
    halign = center
    valign = center
}

# INPUT FIELD
input-field {
    monitor =
    size = 235, 50
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgb(3c3836)
    inner_color = rgb(282828)
    font_color = rgb(ebdbb2)
    fade_on_empty = false
    placeholder_text = Logged in as $USER
    hide_input = false
    check_color = $accent
    fail_color = rgb(fb4934)
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    font_family = monospace
    capslock_color = rgb(fabd2f)
    position = 0, -35
    halign = center
    valign = center
}
