-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- See https://wiki.hypr.land/Configuring/Keywords/

local mainMod = "SUPER"

-- Sets "Windows" key as main modifier

-- NOTE: `terminal`, `fileManager`, `menu`, `browser` below are intentionally
-- NOT `local` — old hyprlang's `$terminal = kitty` etc. (defined in
-- hyprland.conf) were visible here via `source =`, which shares one flat
-- namespace. Lua's `require()` does not share locals across files, so
-- hyprland.lua must set these as plain Lua globals BEFORE requiring this
-- file, or every exec_cmd(...) call below is a nil reference.

hl.bind(mainMod .. " + " .. "q", hl.dsp.window.close())

hl.bind(mainMod .. " + " .. "M", hl.dsp.exec_cmd("command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit"))

hl.bind(mainMod .. " + " .. "E", hl.dsp.exec_cmd(fileManager))

hl.bind(mainMod .. " + " .. "V", hl.dsp.window.float({ action = "toggle" }))

hl.bind(mainMod .. " + " .. "SPACE", hl.dsp.exec_cmd(menu))

hl.bind(mainMod .. " + " .. "P", hl.dsp.window.pseudo())

-- dwindle

hl.bind(mainMod .. " + " .. "RETURN", hl.dsp.exec_cmd(terminal))

hl.bind(mainMod .. " + " .. "w", hl.dsp.exec_cmd("pkill waybar; waybar"))

hl.bind(mainMod .. " + " .. "b", hl.dsp.exec_cmd(browser))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "x", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.local/bin/power-menu"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "t", hl.dsp.exec_cmd(os.getenv("HOME") .. "/Dotfiles/scripts/.local/bin/wallpaper-picker"))

-- Control Center (AGS) — waybar's network/bluetooth icons keep opening iwgtk/blueman-manager directly (see TODO.md), so this is ControlCenter's only trigger.
hl.bind(mainMod .. " + " .. "c", hl.dsp.exec_cmd("ags request -i jjsanchezc-shell toggle-cc"))

-- Move focus with mainMod + arrow keys

hl.bind(mainMod .. " + " .. "h", hl.dsp.focus({ direction = "left" }))

hl.bind(mainMod .. " + " .. "l", hl.dsp.focus({ direction = "right" }))

hl.bind(mainMod .. " + " .. "k", hl.dsp.focus({ direction = "up" }))

hl.bind(mainMod .. " + " .. "j", hl.dsp.focus({ direction = "down" }))

-- Window movement
-- NOTE: hyprconf2lua v1.4.0 emitted these 4 binds with a bare
-- `{ direction = "l" }` table as the dispatcher argument, with no
-- hl.dsp.window.move(...) wrapper at all — the dispatcher call itself was
-- silently dropped. Reconstructed to match the hl.dsp.window.move({...})
-- shape used elsewhere in this same file, and switched "l"/"r"/"u"/"d" to
-- the full-word direction values ("left"/"right"/"up"/"down") to match the
-- convention confirmed for hl.dsp.focus({direction=...}) just above.

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "h", hl.dsp.window.move({ direction = "left" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "l", hl.dsp.window.move({ direction = "right" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "k", hl.dsp.window.move({ direction = "up" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "j", hl.dsp.window.move({ direction = "down" }))

-- Switch workspaces with mainMod + [0-9]

hl.bind(mainMod .. " + " .. 1, hl.dsp.focus({ workspace = 1 }))

hl.bind(mainMod .. " + " .. 2, hl.dsp.focus({ workspace = 2 }))

hl.bind(mainMod .. " + " .. 3, hl.dsp.focus({ workspace = 3 }))

hl.bind(mainMod .. " + " .. 4, hl.dsp.focus({ workspace = 4 }))

hl.bind(mainMod .. " + " .. 5, hl.dsp.focus({ workspace = 5 }))

hl.bind(mainMod .. " + " .. 6, hl.dsp.focus({ workspace = 6 }))

hl.bind(mainMod .. " + " .. 7, hl.dsp.focus({ workspace = 7 }))

hl.bind(mainMod .. " + " .. 8, hl.dsp.focus({ workspace = 8 }))

hl.bind(mainMod .. " + " .. 9, hl.dsp.focus({ workspace = 9 }))

hl.bind(mainMod .. " + " .. 0, hl.dsp.focus({ workspace = 10 }))

-- Move active window to a workspace with mainMod + SHIFT + [0-9]

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 1, hl.dsp.window.move({ workspace = 1 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 2, hl.dsp.window.move({ workspace = 2 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 3, hl.dsp.window.move({ workspace = 3 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 4, hl.dsp.window.move({ workspace = 4 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 5, hl.dsp.window.move({ workspace = 5 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 6, hl.dsp.window.move({ workspace = 6 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 7, hl.dsp.window.move({ workspace = 7 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 8, hl.dsp.window.move({ workspace = 8 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 9, hl.dsp.window.move({ workspace = 9 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 0, hl.dsp.window.move({ workspace = 10 }))

-- Example special workspace (scratchpad)
-- Moved off Super+S/Super+Shift+S 2026-08-09 to make room for screenshots
-- (Super+M was already taken by hyprshutdown/exit, so this went to G instead).

hl.bind(mainMod .. " + " .. "G", hl.dsp.workspace.toggle_special("magic"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "G", hl.dsp.window.move({ workspace = "special:magic" }))

-- Screenshots

hl.bind(mainMod .. " + " .. "S", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.local/bin/region-capture"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "S", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.local/bin/full-capture"))

-- Scroll through existing workspaces with mainMod + scroll

hl.bind(mainMod .. " + " .. "mouse_down", hl.dsp.focus({ workspace = "e+1" }))

hl.bind(mainMod .. " + " .. "mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging

hl.bind(mainMod .. " + " .. "mouse:272", hl.dsp.window.drag(), { mouse = true })

hl.bind(mainMod .. " + " .. "mouse:273", hl.dsp.window.resize(), { mouse = true })

hl.bind(mainMod .. " + " .. "f", hl.dsp.window.fullscreen())

-- Laptop multimedia keys for volume and LCD brightness

-- NOTE: original used `bindel` (locked + repeat-while-held), but
-- hyprconf2lua v1.4.0 dropped the repeat flag for all 4 of these — added
-- `repeating = true` back so holding the key still repeats.

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })

hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { locked = true, repeating = true })

hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true, repeating = true })

hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { locked = true, repeating = true })

-- Requires playerctl

hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })

hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })

hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })

hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

-- Asus ROG Specific keys
-- NOTE: hyprconf2lua v1.4.0 emitted these as bare numbers (156, 211, ...).
-- Old hyprlang auto-detected a purely-numeric key string as a raw keycode;
-- hl.bind() does not — confirmed via a nested-Hyprland smoke test, which
-- failed all 10 of these with `Unknown keysym: "156"` etc. Fix: prefix with
-- "code:" per https://wiki.hypr.land/Configuring/Basics/Binds/.

hl.bind("code:156", hl.dsp.exec_cmd("rog-control-center"))

-- ASUS Armory crate key

hl.bind("code:211", hl.dsp.exec_cmd("asusctl profile next"))

-- Fan Profile key switch between power profiles

hl.bind("code:121", hl.dsp.exec_cmd("pamixer -t"))

-- Speaker Mute FN+F1

hl.bind("code:122", hl.dsp.exec_cmd("pamixer -d 5"))

-- Volume lower key

hl.bind("code:123", hl.dsp.exec_cmd("pamixer -i 5"))

-- Volume Higher key

hl.bind("code:256", hl.dsp.exec_cmd("pamixer --default-source -t"))

-- Mic mute key

hl.bind("code:232", hl.dsp.exec_cmd("brightnessctl set 10%-"))

-- Screen brightness down FN+F7

hl.bind("code:233", hl.dsp.exec_cmd("brightnessctl set 10%+"))

-- Screen brightness up FN+F8

hl.bind("code:237", hl.dsp.exec_cmd("brightnessctl -d asus::kbd_backlight set 33%-"))

-- Keyboard brightness down FN+F2

hl.bind("code:238", hl.dsp.exec_cmd("brightnessctl -d asus::kbd_backlight set 33%+"))

-- Keyboard brightness up FN+F3

-- Clipboard history



hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "V", hl.dsp.exec_cmd("cliphist list| rofi -dmenu -p \"\"| cliphist decode| wl-copy"))

-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
end)
