$accent = rgb(f5bd6f)
$accentAlpha = rgba(245, 189, 111, 0.8)
$text = rgb(ede0d4)
$background = rgb(18120b)
$font = JetBrainsMono Nerd Font

# GENERAL
general {
    disable_loading_bar = true
    hide_cursor = true
}

# BACKGROUND
background {
    monitor =
    path = ~/Dotfiles/hypr/Wallpapers/dark/allmight-dark.jpg
    blur_passes = 2
}

# TIME
label {
    monitor =
    text = $TIME12
    color = $accent
    font_size = 52
    font_family = $font
    position = 27, 0
    halign = left
    valign = top
}

# DATE
label {
    monitor =
    text = cmd[update:43200000] date +"%A, %d %B %Y"
    color = $text
    font_size = 20
    font_family = $font
    position = 30, -90
    halign = left
    valign = top
}

# USER AVATAR

image {
    monitor =
    path = ~/.face
    size = 100
    border_color = $accent

    position = 0, 75
    halign = center
    valign = center
}

# INPUT FIELD
input-field {
    monitor =
    size = 235, 50
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgb(251f17)
    inner_color = rgb(18120b)
    font_color = rgb(ede0d4)
    fade_on_empty = false
    placeholder_text = Logged in as $USER
    hide_input = false
    check_color = $accent
    fail_color = rgb(ffb4ab)
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    font_family = monospace
    capslock_color = rgb(b8cda1)
    position = 0, -35
    halign = center
    valign = center
}
